### ISSUE TITLE
webp-files are hidden globally in file manager

### ISSUE THREAD

**Issue by heural** [plan2net/webp#56]
Typo3 filemanager (filelist/fal) does not display webp-files anymore if this extension is installed:
https://forge.typo3.org/issues/94921

This extension disables webp-files globally in the file-manager. Why?

Should hide only "generated" webp-files or hide the special folder __processed__ instead?

**Comment by wazum** [comment]
Why?
Because the files are possibly generated in every folder.

Create an extension and remove the filter yourself from `$GLOBALS['TYPO3_CONF_VARS']['SYS']['fal']['defaultFilterCallbacks']`
or file a feature request to make this configurable (possibly sponsored).

**Comment by a-r-m-i-n** [comment]
It would be nice, if this would be configurable. A customer of mine, uses webp images from its own, and is wondering, why they are missing all in fileadmin. 

Also, because of the numeric index you use, it is more complicated to remove just your filter. You could provide an extension setting for this.
