### ISSUE TITLE
Output correct path to webp file instead of rewriting all png/gif/jpeg files and append ".webp"

### ISSUE THREAD

**Issue by simonschaufi** [plan2net/webp#68]
I still have static files that I want to link to without an automatic rewrite to webp simply because they don't exist. Insted TYPO3 should know which files exist as webp and then output the "real" path to the webp file instead of the global "rewrite everyting".

**Comment by wazum** [comment]
Help me to understand your issue … the (server) rewrite rules test for files with the same name, but .webp extension, if the file is not there nothing happens anyway (the server returns the original file) …
What exactly would you expect? Please give me some examples.

**Comment by simonschaufi** [comment]
My expectation is that TYPO3 will output `/fileadmin/_processed_/9/4/csm_xxx_d103b75947.webp` directly without any redirect necessary

**Comment by wazum** [comment]
Hm, not really, because you link to the original files in the TYPO3 backend. So, maybe it's possible, but that's something outside the scope of my extension. You can try to solve this one yourself.
Create a new storage driver (implementing \TYPO3\CMS\Core\Resource\Driver\DriverInterface) and adapt the `getFile…` methods there.

The another problem is, that not all browsers support webp …

hth
