### ISSUE TITLE
Allow to clear/remove the generated files outside of the processed folder

### ISSUE THREAD

**Issue by M4rt1n17** [plan2net/webp#7]
This is no issue just a Feature Request to make changing config of this extension more easy.

Problem:
When u already have generated webp's of your pics and want to change the setting you would manualy have to access the Server/FTP and delete all webp files from /fileadmin/

Solution:
Implementing a button which is deleting recursive all **.(jpe?g/png).webp** files from /fileadmin/ would make it much easier to delete the webp which got generated with old config.

Also this function could automaticaly get triggered when someone "Remove Temporary Assets" in the maintenance tool.

**Comment by wazum** [comment]
I do not like the current implementation (of the last feature request) 100% anyway, so I'll definitely think about how to identify/separate these (temporary) files outside the _processed_ folder more clearly (to be e.g. be able to delete them via Install Tool) and will come up with a solution or discard the recently introduced changes at all.

**Comment by wazum** [comment]
Clearing the temporary assets (Screenshot from TYPO3 CMS 9)
![Screenshot 2019-03-19 at 09 46 22](https://user-images.githubusercontent.com/146727/54592074-e656ad00-4a2b-11e9-8a00-955166c75318.png)
already removes the .webp files created by this extension.
It's not very obvious because the wizard only shows the _processed_ directory, but all other processed files are deleted as well outside this folder.
