### ISSUE TITLE
Describe how to exclude webp for directories

### ISSUE THREAD

**Issue by georgringer** [plan2net/webp#77]
If files of a directory should be exclude a htaccess file with

```
RewriteEngine off
```

can be used.

Alternatively it would be cool to have a extension configuration with paths like "1:/fo/bar,0:typo3conf/ext/theme/" which are then exluded using a simple str_starts_with would be a nice feature

**Comment by cyMarvin** [comment]
@georgringer thanks for the hint!

I'd appreciate an exclusion mechanism as well, since this trick does not work for the processed versions of these files.

Maybe adding a checkbox to file metadata could be an option, too.
Editors would then have the possibility to exclude single files, that might not translate well into WebP format.

**Comment by wazum** [comment]
Added a new option in 5.0.0 (TYPO3 CMS 12)
