### ISSUE TITLE
Avif support

### ISSUE THREAD

**Issue by ogrosko** [plan2net/webp#94]
Hello, is there a plan to support AVIF file format?

**Comment by rubensilva09** [comment]
Hi,

Since `GraphicalFunctions` doesn't support this format on version up to TYPO3 12 I think it's a no-go for now.
I've, however, been able to adapt the extension to make it run on v13 and actually render some AVIF files since they've [integrated AVIF support](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.3/Feature-102353-AVIFSupportForImagesGeneratedByGIFBUILDER.html).

**Comment by ogrosko** [comment]
@rubensilva09 cool we will check it

thx

**Comment by wazum** [comment]
Heads-up: AVIF (and JPEG XL) support landed in `master` and will ship with the next release. Set `formats_enabled = webp,avif` in the Extension Configuration to enable AVIF alongside the existing WebP sibling, or include `jxl` for all three. Each format has its own `converter_<format>` / `parameters_<format>` / `mime_types_<format>` keys; the converter × format matrix (libvips / ImageMagick / external / PHP GD) is in the README.

Thanks for the original request!
