### ISSUE TITLE
Undefined array key "processor_stripColorProfileCommand" for TYPO3 11.5

### ISSUE THREAD

**Issue by AlenBilalovic** [plan2net/webp#98]
Hello,

The fix for processor_stripColorProfileCommand has only been merged into v5 for TYPO3 v12 but the same issue is happening in TYPO3 11.5.

Related issue
https://github.com/plan2net/webp/pull/93

Any chance you can make a version release for v4 with the included fix.

Any info you need, just let me know.

Thanks in advance

**Comment by wazum** [comment]
I'll take a look at it.

**Comment by wazum** [comment]
@AlenBilalovic  I pushed a tag 4.3.0 with the fix, please test and report if it works for you

**Comment by peterschoene** [comment]
With the fix 4.3.0 I get
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Undefined constant TYPO3\CMS\Core\Utility\CommandUtility::escapeShellArgument | Error thrown in file typo3conf/ext/webp/Classes/Converter/MagickConverter.php in line 62.

I fixed it with 

[CommandUtility::class, 'escapeShellArgument'],
in line 62 instead of 
CommandUtility::escapeShellArgument(...),

Is this correct?
